language: java

jdk:
 - oraclejdk8

install:
 - mvn install

after_success:
  - mvn -pl '!spring-cloud-zuul-ratelimit-dependencies' clean jacoco:prepare-agent verify jacoco:report coveralls:report

notifications:
  email:
   - marcos.hgb@gmail.com