language: java

jdk:
 - oraclejdk8

install:
 - mvn install

script:
  - mvn clean verify

after_success:
  - mvn clean verify jacoco:report coveralls:report

notifications:
  email:
   - marcos.hgb@gmail.com