zuul:
  routes:
    serviceA:
      path: /serviceA
      url: forward:/services
    serviceB:
      path: /serviceB
      url: forward:/services
    serviceC:
      path: /serviceC
      url: forward:/services
  ratelimit:
    enabled: true
    policies:
      serviceA:
        limit: 10
        refresh-interval: 60
        type:
          - origin
      serviceB:
        limit: 2
        refresh-interval: 5
        type:
          - origin
  strip-prefix: true
