version: 1
update_configs:
    - package_manager: "maven:java"
    directory: "/"
    update_schedule: "daily"

    # Apply default reviewer and label to created
    # pull requests
    default_reviewers:
      - "marcosbarbero"
    default_labels:
      - "dependencies
    allowed_updates:
      - match:
          update_type: "all"
